export const REQUEST_ARTICULOS = "REQUEST_ARTICULOS";
export const RECEIVE_ARTICULOS = "RECEIVE_ARTICULOS";
export const FAILURE_ARTICULOS = "FAILURE_ARTICULOS";

export const CREATE_ARTICULO_REQUEST = "CREATE_ARTICULO_REQUEST";
export const CREATE_ARTICULO_SUCCESS = "CREATE_ARTICULO_SUCCESS";
export const CREATE_ARTICULO_FAILURE = "CREATE_ARTICULO_FAILURE";

export const DELETE_ARTICULO_REQUEST = "DELETE_ARTICULO_REQUEST";
export const DELETE_ARTICULO_SUCCESS = "DELETE_ARTICULO_SUCCESS";
export const DELETE_ARTICULO_FAILURE = "DELETE_ARTICULO_FAILURE";

export const UPDATE_ARTICULO_REQUEST = "UPDATE_ARTICULO_REQUEST";
export const UPDATE_ARTICULO_SUCCESS = "UPDATE_ARTICULO_SUCCESS";
export const UPDATE_ARTICULO_FAILURE = "UPDATE_ARTICULO_FAILURE";