export const REQUEST_ARTICULOS = "REQUEST_ARTICULOS";
export const RECEIVE_ARTICULOS = "RECEIVE_ARTICULOS";
export const FAILURE_ARTICULOS = "FAILURE_ARTICULOS";

export const CREATE_ARTICULO_REQUEST = "CREATE_ARTICULO_REQUEST";
export const CREATE_ARTICULO_SUCCESS = "CREATE_ARTICULO_SUCCESS";
export const CREATE_ARTICULO_FAILURE = "CREATE_ARTICULO_FAILURE";